### ISSUE TITLE
Released version either as source or docker repo that actually works

### ISSUE THREAD

**Issue by LarsMilland** [fabric8io/fabric8-ipaas#191]
Hi

I am trying to stitch together an Fabric8 platform primarily for Java based applications with OpenShift and the Fabric8MQ and ActiveMQ based templates as I understand comes from this repository.

Though none of the recent versions appears to actually work. The most recent one 2.2.90 and the snapshot version 2.2.91-SNAPSHOT appears to fail on the basic start of the ActiveMQ broker.

org.jboss.weld.exceptions.DeploymentException: WELD-000123: Error loading io.fabric8.cdi.weld.ClientProducer defined in <class>io.fabric8.cdi.weld.ClientProducer</class> in jar:file:/deployments/lib/fabric8-cdi-2.2.91-tests.jar!/META-INF/beans.xml@21
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:269)
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:256)
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:572)
        at java.util.AbstractList$Itr.next(AbstractList.java:358)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:378)
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder.createModuleEnablement(GlobalEnablementBuilder.java:233)
        at org.jboss.weld.bootstrap.BeanDeployment.createEnablement(BeanDeployment.java:219)
        at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:377)
        at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:76)
        at org.jboss.weld.environment.se.Weld.initialize(Weld.java:146)
        at io.fabric8.amq.Main.main(Main.java:31)
Caused by: java.lang.NoClassDefFoundError: org/easymock/IAnswer
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getDeclaredConstructors(Class.java:2020)
        at org.jboss.weld.environment.deployment.WeldResourceLoader.classForName(WeldResourceLoader.java:52)
        at org.jboss.weld.bootstrap.enablement.GlobalEnablementBuilder$ClassLoader.apply(GlobalEnablementBuilder.java:267)

Can you point to a tag in either the master branch or another branch that have "release quality" which I can trust to start from?

Best regards
Lars Milland

**Comment by jstrachan** [comment]
sorry about that; looks like some maven dependencies broke the amqbroker docker image. Just testing; pushing a fix shortly

**Comment by LarsMilland** [comment]
Hi

Thanx for the quick response - are you, as in James Strachan maybe also able to investigate a maybe similar problem with the Fabric8MQ classpath/dependency setup where a launch of the docker image from the build replies:

[vagrant@vagrant ~]$ docker run -i -t fabric8/fabric8mq:2.2.91-SNAPSHOT
I> No access restrictor found, access to all MBean is allowed
I> No suitable address found for listening on multicast discovery requests
Jolokia: Agent started with URL http://172.17.0.2:8778/jolokia/
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at io.fabric8.mq.Main.<clinit>(Main.java:24)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more

**Comment by jstrachan** [comment]
FWIW my release, `fabric8/fabric8mq:2.2.90` starts up fine, as does a local build of master too

**Comment by jstrachan** [comment]
BTW the docker images tend to expect some environment variables. Try running it via
```
mvn docker:build fabric8:apply
```
then it'll run correctly inside kubernetes/openshift

**Comment by LarsMilland** [comment]
Probably my mistake then - I will run it via the appropiate procedure, with AMQBroker and Fabric8MQ package launcher through "mvn docker:build fabric8:apply".
