### ISSUE TITLE
msg-gateway fails to find artemis endpoints

### ISSUE THREAD

**Issue by rajdavies** [fabric8io/fabric8-ipaas#226]
The msg-gateway looks for artemis endpoints - but fails with the following exception:

FAILED lookupBrokers
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/artemis. Message: User "system:serviceaccount:default:default" cannot get endpoints in project "default". Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], kind=endpoints, name=artemis, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=User "system:serviceaccount:default:default" cannot get endpoints in project "default", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:264)[jar:file:/app/msg-gateway-2.2.94-SNAPSHOT.jar!/lib/kubernetes-client-1.3.69.jar!/:]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:235)[jar:file:/app/msg-gateway-2.2.94-SNAPSHOT.jar!/lib/kubernetes-client-1.3.69.jar!/:]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:208)[jar:file:/app/msg-gateway-2.2.94-SNAPSHOT.jar!/lib/kubernetes-client-1.3.69.jar!/:]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:197)[jar:file:/app/msg-gateway-2.2.94-SNAPSHOT.jar!/lib/kubernetes-client-1.3.69.jar!/:]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:506)[jar:file:/app/msg-gateway-2.2.94-SNAPSHOT.jar!/lib/kubernetes-client-1.3.69.jar!/:]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:114)[jar:file:/app/msg-gateway-2.2.94-SNAPSHOT.jar!/lib/kubernetes-client-1.3.69.jar!/:]
	at io.fabric8.msg.gateway.brokers.impl.KubernetesBrokerControl.lookupBrokers(KubernetesBrokerControl.java:127)[jar:file:/app/msg-gateway-2.2.94-SNAPSHOT.jar!/:]
	at io.fabric8.msg.gateway.brokers.impl.KubernetesBrokerControl.lambda$start$0(KubernetesBrokerControl.java:72)[jar:file:/app/msg-gateway-2.2.94-SNAPSHOT.jar!/:]
	at io.fabric8.msg.gateway.brokers.impl.KubernetesBrokerControl$$Lambda$2/2143226352.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_51]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_51]

**Comment by jimmidyson** [comment]
Security! All requests to the API server are secured & the user making the requests needs to be granted karma to do so. If you're running in a pod then the user querying the API server is the service account (the account the pod effectively runs under). You can see from the stack trace it says: `User "system:serviceaccount:default:default" cannot get endpoints in project "default"`. So this pod is running under the `system:serviceaccount:default:default` service account & querying the API server as this users. That user hasn't been granted karma to do so...

There are 2 options to work around this:

* Run as a different service account (add `<fabric8,serviceAccount>yourNewServiceAccount</fabric8.serviceAccount>` to your pom & then grant karma to that service account via `oc adm` (or `oadm`) with `oc adm policy add-role-to-user view system:serviceaccount:default:yourNewServiceAccount`. Note that the `default` part is the name of the namespace you are deploying into. You'll then need to redeploy/restart pods so that the service account the pod runs under will have this new role.
* Switch to using headless service & DNS (yay!) querying SRV records. This removes any need to query the API server & no new permissions. Headless services have SRV records created for every service endpoint & so can be used for discovery.

As you might guess, I prefer the DNS option personally as it removes any need for new service accounts, granting karma, etc & works out of the box.

**Comment by rajdavies** [comment]
This is fixed
