### ISSUE TITLE
NATS load tests fails intermittently

### ISSUE THREAD

**Issue by KurtStam** [fabric8io/fabric8-ipaas#338]
NatsClient{"verbose":"false","pedantic":"false","sslRequired":"false","user":"null","pass":null,"name":sb,"lang":,"version":java}
JNatsd shutdown
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.866 sec <<< FAILURE! - in io.fabric8.msg.jnatsd.TestLoad
testLoad(io.fabric8.msg.jnatsd.TestLoad)  Time elapsed: 15.866 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<102460>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.fabric8.msg.jnatsd.TestLoad.testLoad(TestLoad.java:76)

**Comment by KurtStam** [comment]
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.064 sec <<< FAILURE! - in io.fabric8.msg.jnatsd.TestLoad
testLoad(io.fabric8.msg.jnatsd.TestLoad)  Time elapsed: 10.059 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<687>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.fabric8.msg.jnatsd.TestLoad.testLoad(TestLoad.java:79)
