### ISSUE TITLE
Gateway can't store into ElasticSearch

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-ipaas#350]
When we deploy apiman, apiman-gateway & elasticsearch with SSL/TLS, this error is reported within the log of the gateway

```
07:01:03,021  INFO Idle connection reaping disabled...
Exception in thread "ESRegistryCacheInvalidator" java.lang.RuntimeException: java.lang.Exception: Failed to create index: '.apiman_gateway' Reason: AuthException[com.floragunn.searchguard.authentication.AuthException: No user ${apiman.es.username} or wrong password (digest: plain/none)]; nested: AuthException[No user ${apiman.es.username} or wrong password (digest: plain/none)]; 
	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:68)
	at io.apiman.gateway.engine.es.SimpleJestClientFactory.createJestClient(SimpleJestClientFactory.java:112)
	at io.apiman.gateway.engine.es.SimpleJestClientFactory.createClient(SimpleJestClientFactory.java:59)
	at io.apiman.gateway.engine.es.AbstractESComponent.createClient(AbstractESComponent.java:61)
	at io.apiman.gateway.engine.es.AbstractESComponent.getClient(AbstractESComponent.java:51)
	at io.apiman.gateway.engine.es.PollCachingESRegistry.checkCacheVersion(PollCachingESRegistry.java:204)
	at io.apiman.gateway.engine.es.PollCachingESRegistry$6.run(PollCachingESRegistry.java:180)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Failed to create index: '.apiman_gateway' Reason: AuthException[com.floragunn.searchguard.authentication.AuthException: No user ${apiman.es.username} or wrong password (digest: plain/none)]; nested: AuthException[No user ${apiman.es.username} or wrong password (digest: plain/none)]; 
	at io.apiman.gateway.engine.es.AbstractClientFactory.createIndex(AbstractClientFactory.java:87)
	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:65)
```

**Comment by KurtStam** [comment]
@cmoulliard Can you try again with the latest code?

**Comment by KurtStam** [comment]
Please reopen if this is still an issue for you.
