### ISSUE TITLE
unable to find valid certification path to requested target with Apiman Gateway

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-ipaas#367]
The pod of Apiman Gateway reports this error within its log 

```
10:26:54,333  INFO Node Discovery disabled...
10:26:54,333  INFO Idle connection reaping disabled...
Error adding metric to ES:
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:68)
	at io.apiman.gateway.engine.es.SimpleJestClientFactory.createJestClient(SimpleJestClientFactory.java:112)
	at io.apiman.gateway.engine.es.SimpleJestClientFactory.createClient(SimpleJestClientFactory.java:59)
	at io.apiman.gateway.engine.es.AbstractESComponent.createClient(AbstractESComponent.java:61)
	at io.apiman.gateway.engine.es.AbstractESComponent.getClient(AbstractESComponent.java:51)
	at io.apiman.gateway.engine.es.ESMetrics.processQueue(ESMetrics.java:103)
	at io.apiman.gateway.engine.es.ESMetrics$1.run(ESMetrics.java:86)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:50)
	at io.apiman.gateway.engine.es.AbstractClientFactory.initializeClient(AbstractClientFactory.java:61)
	... 7 more
```

**Comment by KurtStam** [comment]
You will need to deploy ES, Gateway and Apiman in that order. This so it can trust the certs created during the build. Apiman depends on Gateway, and both depend on ES. Each build recreates the self signed certs.

**Comment by cmoulliard** [comment]
This is what I have done (ES -> gateway -> apiman). I will make a new test

**Comment by cmoulliard** [comment]
Problem is still there after doing a fresh installation this morning and following the steps (ES -> Gateway & Apiman)

**Comment by cmoulliard** [comment]
Here is the log reported

```
Error adding metric to ES:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:50)
        at io.apiman.gateway.engine.es.ESMetrics.processQueue(ESMetrics.java:103)
        at io.apiman.gateway.engine.es.ESMetrics$1.run(ESMetrics.java:86)
        at java.lang.Thread.run(Thread.java:745)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
        ... 23 more
```

The side effect is that sometimes I can use the Gateway and sometimes no

````
http --verify=no -a demo:demo https://apiman-gateway.vagrant.f8/gateway/demo/cdi-cxf/3.0/customerservice/customers/123
HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 158
Content-Type: application/xml
Date: Mon, 13 Jun 2016 09:23:20 GMT
Server: Jetty(9.2.10.v20150310)
Set-Cookie: 46d675dd3a061ebeea271898912b0776=7a8374cf2964c7ef745c1204a5ec8889; path=/; HttpOnly

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Customer xmlns="http://cxfcdi.fabric.quickstarts.fabric8.io/"><id>123</id><name>John</name></Customer>


OR

http --verify=no -a demo:demo https://apiman-gateway.vagrant.f8/gateway/demo/cdi-cxf/3.0/customerservice/customers/123
HTTP/1.1 500 Server Error
Content-Type: application/json
Date: Mon, 13 Jun 2016 09:22:02 GMT
Server: Jetty(9.2.10.v20150310)
Transfer-Encoding: chunked

{"responseCode":500,"message":null,"trace":"io.apiman.gateway.engine.beans.exceptions.RequestAbortedException\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.abort(ApiRequestExecutorImpl.java:721)
````

**Comment by cmoulliard** [comment]
Question : I don't see that we allow to configure the JestClient (https://github.com/apiman/apiman/blob/apiman-1.2.6.Final/gateway/engine/es/src/main/java/io/apiman/gateway/engine/es/SimpleJestClientFactory.java#L70) to access the ElasticSearch backend using TLS/SSL Protocol. Is it supported ?

Remark : jest supports it --> https://github.com/searchbox-io/Jest/tree/master/jest#https--ssl

**Comment by EricWittmann** [comment]
Not supported in core apiman (yet).  But supported in f8/openshift:

https://github.com/fabric8io/fabric8-ipaas/blob/master/apiman/src/main/java/io/fabric8/apiman/Fabric8EsClientFactory.java

**Comment by cmoulliard** [comment]
As we set this property `setConfigProperty("apiman-gateway.registry.client.type", Fabric8GatewayEsClientFactory.class.getName());)` and that the jestclient is well configured with SSL `httpConfig.sslSocketFactory(sslSocketFactory); `, I don't understand why Apiman will finally create a SimpleJestClient

**Comment by KurtStam** [comment]
I'm turning off metrics: https://github.com/fabric8io/fabric8-ipaas/commit/5faa393b306b3fa9f552cc0258a96c5b45935ef1

We DO import the ES cert though, so not really sure why you are seeing this.
