### ISSUE TITLE
io.apiman.manager.api.rest.contract.exceptions.InvalidApiStatusException: Could not complete action: API was in the wrong status

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-ipaas#370]
```
12:05:56,642  INFO apiman.io/publish annotation value is set to null
12:05:56,642  INFO Namespace: demo
Got organization demo: OrganizationBean [id=demo, name=demo, description=Namespace 'demo' created by Kubernetes2Apiman, createdBy=admin, createdOn=Fri Jun 10 09:36:41 UTC 2016, modifiedBy=admin, modifiedOn=Fri Jun 10 09:36:41 UTC 2016]
RESTEASY010585: JaxrsInjectionTarget skipping validation outside of Resteasy context
12:05:56,844 ERROR Kubernetes2Apiman mapping Exception. 
io.apiman.manager.api.rest.contract.exceptions.InvalidApiStatusException: Could not complete action: API was in the wrong status.
	at io.apiman.manager.api.rest.impl.util.ExceptionFactory.invalidApiStatusException(ExceptionFactory.java:248)
	at io.apiman.manager.api.rest.impl.OrganizationResourceImpl.deleteApiPolicy(OrganizationResourceImpl.java:2324)
	at io.apiman.manager.api.rest.impl.OrganizationResourceImpl$Proxy$_$$_WeldClientProxy.deleteApiPolicy(Unknown Source)
	at io.fabric8.apiman.rest.Kubernetes2ApimanFilter.deleteApi(Kubernetes2ApimanFilter.java:493)
	at io.fabric8.apiman.rest.Kubernetes2ApimanFilter.syncKubernetesToApiman(Kubernetes2ApimanFilter.java:278)
	at io.fabric8.apiman.rest.Kubernetes2ApimanFilter$1.load(Kubernetes2ApimanFilter.java:140)
	at io.fabric8.apiman.rest.Kubernetes2ApimanFilter$1.load(Kubernetes2ApimanFilter.java:138)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at io.fabric8.apiman.rest.Kubernetes2ApimanFilter.doFilter(Kubernetes2ApimanFilter.java:163)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.fabric8.apiman.rest.BearerTokenFilter.doFilter(BearerTokenFilter.java:113)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.fabric8.apiman.rest.BootstrapFilter.doFilter(BootstrapFilter.java:259)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:59)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by KurtStam** [comment]
How to reproduce this?

**Comment by cmoulliard** [comment]
We can close it as Apiman can talk to the Gateway using HTTPS
