### ISSUE TITLE
Gateway connection is interrupted - Not Connected

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-ipaas#382]
The connection with the gateway is interrupted. sometimes it works, sometimes no

- Version of Apiman Gateway : 1.2.6.Final
- Version of OSEv3 : v1.3.0-alpha.1-6e83535

Here are 3 requests performed at 1 second of interval

- 13:39:51 - Fail
- 13:39:58 - Fail
- 13:40:04 - Success

```
io.apiman.gateway.engine.beans.exceptions.ConnectorException: Not connected.		
    at io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:175)		
    at io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:161)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.handleStream(ApiRequestExecutorImpl.java:693)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$3(ApiRequestExecutorImpl.java:268)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$9/353599555.handle(Unknown Source)		
    at io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:211)		
    at io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$4(ApiRequestExecutorImpl.java:271)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$7/847326435.handle(Unknown Source)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:595)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$5(ApiRequestExecutorImpl.java:345)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$8/1687690177.handle(Unknown Source)		
    at io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:123)		
    at io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:112)		
    at io.apiman.gateway.engine.es.CachingESRegistry.getApi(CachingESRegistry.java:115)		
    at io.apiman.gateway.engine.impl.SecureRegistryWrapper.getApi(SecureRegistryWrapper.java:112)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:320)		
    at io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:179)		
    at io.apiman.gateway.platforms.servlet.GatewayServlet.service(GatewayServlet.java:79)		
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)		
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)		
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)		
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)		
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)		
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)		
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)		
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)		
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)		
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)		
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)		
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)		
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)		
    at org.eclipse.jetty.server.Server.handle(Server.java:497)		
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)		
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)		
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)		
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)		
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)		
    at java.lang.Thread.run(Thread.java:745)		
    Caused by: io.apiman.gateway.engine.beans.exceptions.ConnectorException: Not connected.		
    at io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.end(HttpApiConnection.java:360)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$2(ApiRequestExecutorImpl.java:263)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$12/1829007077.handle(Unknown Source)		
    at io.apiman.gateway.engine.io.AbstractStream.handleEnd(AbstractStream.java:116)		
    at io.apiman.gateway.engine.policy.Chain.end(Chain.java:193)		
    at io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.end(ApiRequestExecutorImpl.java:706)		
    at io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:172)		
	Caused by: java.io.IOException: Not connected.		
    at io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.end(HttpApiConnection.java:343)		
    ... 44 more		
```

Response

```
dabou-macosx:~/Fuse/Fuse-projects/fabric8/fabric8-installer/vagrant/openshift$ http --verify=no https://apiman-gateway.vagrant.f8/gateway/demo/cxfcdi/1.0/customerservice/customers/123
HTTP/1.1 500 Server Error
Content-Type: application/json
Date: Mon, 13 Jun 2016 13:39:51 GMT
Server: Jetty(9.2.10.v20150310)
Transfer-Encoding: chunked

{"responseCode":500,"message":null,"trace":"io.apiman.gateway.engine.beans.exceptions.RequestAbortedException\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.abort(ApiRequestExecutorImpl.java:721)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:174)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:161)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.handleStream(ApiRequestExecutorImpl.java:693)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$3(ApiRequestExecutorImpl.java:268)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$9/353599555.handle(Unknown Source)\n\tat io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:211)\n\tat io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$4(ApiRequestExecutorImpl.java:271)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$7/847326435.handle(Unknown Source)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:595)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$5(ApiRequestExecutorImpl.java:345)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$8/1687690177.handle(Unknown Source)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:123)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:112)\n\tat io.apiman.gateway.engine.es.CachingESRegistry.getApi(CachingESRegistry.java:115)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper.getApi(SecureRegistryWrapper.java:112)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:320)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:179)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet.service(GatewayServlet.java:79)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:847)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\n\tat java.lang.Thread.run(Thread.java:745)\n"}{"responseCode":500,"message":"io.apiman.gateway.engine.beans.exceptions.ConnectorException: Not connected.","trace":"java.lang.RuntimeException: io.apiman.gateway.engine.beans.exceptions.ConnectorException: Not connected.\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:175)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:161)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.handleStream(ApiRequestExecutorImpl.java:693)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$3(ApiRequestExecutorImpl.java:268)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$9/353599555.handle(Unknown Source)\n\tat io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:211)\n\tat io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$4(ApiRequestExecutorImpl.java:271)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$7/847326435.handle(Unknown Source)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:595)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$5(ApiRequestExecutorImpl.java:345)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$8/1687690177.handle(Unknown Source)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:123)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:112)\n\tat io.apiman.gateway.engine.es.CachingESRegistry.getApi(CachingESRegistry.java:115)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper.getApi(SecureRegistryWrapper.java:112)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:320)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:179)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet.service(GatewayServlet.java:79)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:847)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: io.apiman.gateway.engine.beans.exceptions.ConnectorException: Not connected.\n\tat io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.end(HttpApiConnection.java:360)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$2(ApiRequestExecutorImpl.java:263)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$12/1829007077.handle(Unknown Source)\n\tat io.apiman.gateway.engine.io.AbstractStream.handleEnd(AbstractStream.java:116)\n\tat io.apiman.gateway.engine.policy.Chain.end(Chain.java:193)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.end(ApiRequestExecutorImpl.java:706)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:172)\n\t... 38 more\nCaused by: java.io.IOException: Not connected.\n\tat io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.end(HttpApiConnection.java:343)\n\t... 44 more\n"}

dabou-macosx:~/Fuse/Fuse-projects/fabric8/fabric8-installer/vagrant/openshift$ http --verify=no https://apiman-gateway.vagrant.f8/gateway/demo/cxfcdi/1.0/customerservice/customers/123
HTTP/1.1 500 Server Error
Content-Type: application/json
Date: Mon, 13 Jun 2016 13:39:58 GMT
Server: Jetty(9.2.10.v20150310)
Transfer-Encoding: chunked

{"responseCode":500,"message":null,"trace":"io.apiman.gateway.engine.beans.exceptions.RequestAbortedException\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.abort(ApiRequestExecutorImpl.java:721)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:174)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:161)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.handleStream(ApiRequestExecutorImpl.java:693)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$3(ApiRequestExecutorImpl.java:268)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$9/353599555.handle(Unknown Source)\n\tat io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:211)\n\tat io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$4(ApiRequestExecutorImpl.java:271)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$7/847326435.handle(Unknown Source)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:595)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$5(ApiRequestExecutorImpl.java:345)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$8/1687690177.handle(Unknown Source)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:123)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:112)\n\tat io.apiman.gateway.engine.es.CachingESRegistry.getApi(CachingESRegistry.java:115)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper.getApi(SecureRegistryWrapper.java:112)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:320)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:179)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet.service(GatewayServlet.java:79)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:847)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\n\tat java.lang.Thread.run(Thread.java:745)\n"}{"responseCode":500,"message":"io.apiman.gateway.engine.beans.exceptions.ConnectorException: Not connected.","trace":"java.lang.RuntimeException: io.apiman.gateway.engine.beans.exceptions.ConnectorException: Not connected.\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:175)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:161)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.handleStream(ApiRequestExecutorImpl.java:693)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$3(ApiRequestExecutorImpl.java:268)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$9/353599555.handle(Unknown Source)\n\tat io.apiman.gateway.engine.policy.Chain.handleHead(Chain.java:211)\n\tat io.apiman.gateway.engine.policy.Chain.doApply(Chain.java:150)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$4(ApiRequestExecutorImpl.java:271)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$7/847326435.handle(Unknown Source)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.loadPolicies(ApiRequestExecutorImpl.java:595)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$execute$5(ApiRequestExecutorImpl.java:345)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$8/1687690177.handle(Unknown Source)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:123)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper$1.handle(SecureRegistryWrapper.java:112)\n\tat io.apiman.gateway.engine.es.CachingESRegistry.getApi(CachingESRegistry.java:115)\n\tat io.apiman.gateway.engine.impl.SecureRegistryWrapper.getApi(SecureRegistryWrapper.java:112)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.execute(ApiRequestExecutorImpl.java:320)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet.doAction(GatewayServlet.java:179)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet.service(GatewayServlet.java:79)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:847)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:497)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\n\tat java.lang.Thread.run(Thread.java:745)\nCaused by: io.apiman.gateway.engine.beans.exceptions.ConnectorException: Not connected.\n\tat io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.end(HttpApiConnection.java:360)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl.lambda$null$2(ApiRequestExecutorImpl.java:263)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$$Lambda$12/1829007077.handle(Unknown Source)\n\tat io.apiman.gateway.engine.io.AbstractStream.handleEnd(AbstractStream.java:116)\n\tat io.apiman.gateway.engine.policy.Chain.end(Chain.java:193)\n\tat io.apiman.gateway.engine.impl.ApiRequestExecutorImpl$3.end(ApiRequestExecutorImpl.java:706)\n\tat io.apiman.gateway.platforms.servlet.GatewayServlet$2.handle(GatewayServlet.java:172)\n\t... 38 more\nCaused by: java.io.IOException: Not connected.\n\tat io.apiman.gateway.platforms.servlet.connectors.HttpApiConnection.end(HttpApiConnection.java:343)\n\t... 44 more\n"}

dabou-macosx:~/Fuse/Fuse-projects/fabric8/fabric8-installer/vagrant/openshift$ http --verify=no https://apiman-gateway.vagrant.f8/gateway/demo/cxfcdi/1.0/customerservice/customers/123
HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 158
Content-Type: application/xml
Date: Mon, 13 Jun 2016 13:40:04 GMT
Server: Jetty(9.2.10.v20150310)
Set-Cookie: 46d675dd3a061ebeea271898912b0776=7a8374cf2964c7ef745c1204a5ec8889; path=/; HttpOnly

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Customer xmlns="http://cxfcdi.fabric.quickstarts.fabric8.io/"><id>123</id><name>John</name></Customer>
```

**Comment by cmoulliard** [comment]
This problem is related to a DNS issue that we have since the upgrade to OSE origin 1.3.1.

With Openshift Origin 1.3.1, the first nameserver defined within the docker container is 172.30.0.1 and not 172.28.128.4 like with Openshift Origin 1.1.6. By consequence, the DNS resolution took too much time sometimes and explains why we can access or not the gateway.

the problem is gone since I have reverted to Openshift Origin 1.1.6
